FROM arm32v7/openjdk:8-jre-alpine

RUN apk add curl
COPY jasmarty.jar /app/jasmarty.jar
CMD ["java", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-Xmx90m", "-Dlog4j2.formatMsgNoLookups=True", "-jar", "/app/jasmarty.jar"]
HEALTHCHECK --interval=120s --timeout=10s --retries=3 --start-period=30s CMD curl --user check:check --fail http://localhost:8080/wipf/up || kill 1