FROM arm32v7/openjdk:8-jre-alpine

RUN apk add curl
COPY jasmarty.jar /app/jasmarty.jar
CMD ["java", "-Xmx90m", "-Xmx90m", "-jar", "/app/jasmarty.jar", "–Dlog4j2.formatMsgNoLookups=True"]
HEALTHCHECK --interval=120s --start-period=30s CMD curl --user check:check --fail http://localhost:8080/wipf/up || kill 1
