FROM arm64v8/openjdk:24-bookworm
#FROM arm64v8/debian

# Curl ist bereits installiert
#RUN apt-get update && apt-get install curl && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY jasmarty.jar /app/jasmarty.jar
CMD ["java", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-Xmx90m", "-Dlog4j2.formatMsgNoLookups=True", "-jar", "/app/jasmarty.jar"]
HEALTHCHECK --interval=120s --timeout=10s --retries=3 --start-period=30s CMD curl --user check:check --fail http://localhost:8080/wipf/up || kill 1
