name: Build Jasmarty Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Run tests for any PRs.
  pull_request:
    branches: [master]
    
env:
  IMAGE_NAME: jasmarty

jobs:
  build-jasmarty:

    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Vorbereiten
        run: echo "Starting..." && cd scripts && chmod +x *.sh
      
      - name: Build jar
        run: echo "Starting..." && cd scripts && ./setup.sh && ./buildAll.sh && cp ../target/jasmarty-1.0-SNAPSHOT-runner.jar jasmarty.jar
        
      - name: Save jar
        uses: actions/upload-artifact@v2
        with:
          name: jasmarty.jar
          path: scripts/jasmarty.jar

      # - name: Build and Push dockerimage_arm 32
      #   run: |
      #     IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

      #     # Change all uppercase to lowercase
      #     IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

      #     # Strip git ref prefix from version
      #     VERSION=$(date '+%Y-%m-%d')

      #     echo IMAGE_ID=$IMAGE_ID
      #     echo VERSION=$VERSION

      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      #     cd scripts && \
      #     docker buildx create --driver-opt image=moby/buildkit:master --name mybuilder && \
      #     docker buildx use mybuilder && \
      #     docker buildx build --platform linux/arm -t $IMAGE_ID:${VERSION}-arm -f Dockerfile.arm --push .

      - name: Build and Push dockerimage_arm 64
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(date '+%Y-%m-%d')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          cd scripts && \
          docker buildx create --driver-opt image=moby/buildkit:master --name mybuilder64 && \
          docker buildx use mybuilder64 && \
          docker buildx build --platform linux/arm64 -t $IMAGE_ID:${VERSION}-arm_64 -f Dockerfile.arm_64 --push .

      - name: Build and Push dockerimage
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(date '+%Y-%m-%d')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          cd scripts && \
          docker build -t $IMAGE_ID:${VERSION} -f Dockerfile . && \
          docker push $IMAGE_ID:${VERSION}
