name: Build Jasmarty Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  # Run tests for any PRs.
  pull_request:
    branches: [master]
    
env:
  IMAGE_NAME: jasmarty

jobs:
  build-jasmarty:

    runs-on: ubuntu-24.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Vorbereiten
        run: echo "Starting..." && cd scripts && chmod +x *.sh && java -version
      
      - name: Build jar
        run: echo "Starting..." && cd scripts && ./setup.sh && ./buildAll.sh && ls -lahrt ../target/ && cp ../target/jasmarty-1.0-SNAPSHOT-runner.jar jasmarty.jar

      - name: Build and Push dockerimage
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(date '+%Y-%m-%d')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          cd scripts && \
          docker build -t $IMAGE_ID:${VERSION} -f Dockerfile . && \
          docker push $IMAGE_ID:${VERSION}
